### ISSUE TITLE
Enable comments for blog?

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/old_team_site_nikola#11]
Use Disqus?  https://docs.getnikola.com/en/latest/manual/?highlight=disqus#comments-and-annotations

Any thoughts @mikecroucher and @mondus?

**Comment by mikecroucher** [comment]
I've found that people don't really comment on blog posts too much these days. They tend to leave commentary for social media.

Even if you didn't buy that argument, I don't like the idea of outsourcing comments to disqus. They can control additional content appearing on your blog such as adverts.  See this review for example http://www.wpbeginner.com/opinion/switching-away-from-disqus-review-increased-comments-by-304/ 

I never want to see adverts on this site!
