### ISSUE TITLE
Profile for Becky Arnold on RSE site

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/old_team_site_nikola#134]
@r-j-arnold  Please could you add a profile to the RSE team's site.  
* Info on how to contribute to the site: [README.md](README.md)  This should be clear and up to date; please raise Issues in this repo if not.
* Page you need to edit: [site/pages/contact/team.md](site/pages/contact/team.md).
* Rendered content: https://rse.shef.ac.uk/contact/team/ (hosted on GitHub Pages)

**Comment by r-j-arnold** [comment]
Will do

**Comment by r-j-arnold** [comment]
@willfurnass  I've made the pull request

**Comment by willfurnass** [comment]
Addressed via PR #136
