### ISSUE TITLE
Restructure training page

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/old_team_site_nikola#49]
Separate into 
* (nicer-formatted) events listing and
* Software/Data Carpentry page, giving an overview of how they work plus details of the alumni mailing list, helpers mailing list and Slack.
* (maybe) short guides to various topics 
?

**Comment by mondus** [comment]
I would like to see a separation between training events and on demand content. Some of the past events have permanently available content which can be done at any time. We should catalogue these.

**Comment by mondus** [comment]
No superseded by issue #76
