### ISSUE TITLE
Typo on training page

### ISSUE THREAD

**Issue by mondus** [RSE-Sheffield/old_team_site_nikola#50]
" 2017-01-26 - 2017-01-27: Two-day GPU training course held at the University of Sheffield. The aim of the course was to provide a basic understanding of principles of CUDA GPU programming and GPU programming for people without prior knowledge of CUDA or parallel programming. Delivered by Dr. Paul Richmond (Comp Sci) with assistance from Mozhgan Kabiri Chimeh from the Research Software Engineering Sheffield group. Material can be found here."

..no it cant, but if you take the extraneous "/&gt;" off the end of the link, it can!

To fix on next contribution.

**Comment by willfurnass** [comment]
Fixed
