### ISSUE TITLE
Website Revelopment

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/old_team_site_nikola#71]
New top-level content. See other issues. 

+ [ ] Index
    + About RSE
    + Summary 
    + What WE do
+ [ ] Blog
    + Including new blog posts
+ [x] RSE Service
    + Financial Model
    + Service Model
    + What we do
    + How to work with us 
    + Testimonials
    + Projects
+ [ ] RSE Community
    + Links to community resources (GPU computing, Sheffield geek, Sheffield R) etc
    + Coffee and Cake
    + Seminar Series
    + How to ask for Help
    + Equipment / Resources
+ [x] Training
    + Code Clinic
    + Training Events (Future & Previous)
    + On Demand Training
    + Development of Training
+ [x] Team
    + Group Experience
    + Alumni
+ [x] Contact Us

**Comment by ptheywood** [comment]
Nested navigation elements cannot have an actual page as the top level element.

I.e. to achieve the above `NAVIGATION_LINKS` will probably need to look like:

```
NAVIGATION_LINKS = {
    DEFAULT_LANG: (
        ("/blog","Blog"),
        (
            (
                ('/service', 'Overview'),
                ('/service/financial-model', 'Financial Model'), 
                ('/service/service-model', 'Service Model'),
                ('/service/what-we-do', 'What we do'),
                ('/service/work-with-us', 'How to work with us'),
                ('/service/testimonials', 'Testimonials'),
                ('/service/projects', 'Projects'),
            ), 
            'RSE Service'
        ),
        (
            (
                ('/community', 'Overview'),
                ('/community/coffee-and-cake', 'Coffee and Cake'), 
                ('/community/seminar-series', 'Seminar Series'),
                ('/community/ask-for-help', 'Asking for Help'),
                ('/community/equipment-and-resources', 'Equipment and Resources'),
            ), 
            'RSE Community'
        ),
        (
            (
                ('/training', 'Overview'),
                ('/training/events', 'Training Events'), 
                ('/training/on-demand', 'On Demand Training'),
                ('/training/development', 'Development of Training'),
            ), 
            'Training'
        ),
        (
            (
                ('/team', 'Team'),
                ('/team/alumni', 'Alumni'), 
            ), 
            'Team'
        ),
        ("/contact","Contact Us"),
    ),
}
```

**Comment by mondus** [comment]
First update has been made live. Still some outstanding content which should be done as PRs to new_site branch

**Comment by ptheywood** [comment]
Closing as covered by the new repository.
