### ISSUE TITLE
Website Redevelopment - RSE Community

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/old_team_site_nikola#75]
New top level page, containing the following information / sub-pages:

+ [x] Links to community resources - i.e. GPU Computing, Sheffield Geek, R Users communit
+ [x] Coffee & Cake 
+ [x] Seminar Series
+ [ ] How to ask for help
+ [x] Equipment/Resources

**Comment by mondus** [comment]
All done other than how to ask for help. @annakrystalli is to complete this. Link in navigation can be uncommitted when complete.

**Comment by annakrystalli** [comment]
I'm confused. I thought that was what @pfortiz was working on at the hack. I was working on the Carpentries page

**Comment by mondus** [comment]
@annakrystalli @pfortiz I have put some basic content together for these pages as I wanted the site updating today. Feel free to pull the changes and add something with a bit more information.

**Comment by ptheywood** [comment]
Closing as no longer relevant for the new repository.
