### ISSUE TITLE
Switch to more attractive and/or extensible static site generator

### ISSUE THREAD

**Issue by ptheywood** [RSE-Sheffield/old_team_site_nikola#80]
Possibly port to Jekyll and redevelop the look of the website - should be relatively simple if content is mostly Markdown

**Comment by willfurnass** [comment]
Or Hugo: https://gohugo.io/getting-started/quick-start/  Written in Go: single binary FTW.  Nice example theme: https://themes.gohugo.io/docdock/

**Comment by ptheywood** [comment]
Closing as in progress with the switch to the new repository.
