### ISSUE TITLE
Auto-deploy from devel to master using CI

### ISSUE THREAD

**Issue by willfurnass** [RSE-Sheffield/old_team_site_nikola#85]
Could have two Travis CI: build stages
1. Test every push / pull request to any branch in this repo
2. If push to devel branch then deploy rendered content to master branch

Info on Travis CI build stages: https://docs.travis-ci.com/user/build-stages

FAO @monduus

**Comment by mondus** [comment]
Nice link with instructions: https://getnikola.com/blog/automating-nikola-rebuilds-with-travis-ci.html

We could restrict building and deployment to master only. Otherwise we need some clever way to only deploy the master course branch (`devel`). Thoughts?

**Comment by willfurnass** [comment]
Or instead use a condition in a build stage to limit the deployment to pushes (_not_ pull requests) to devel: https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#conditional-stages

**Comment by willfurnass** [comment]
Done in PR #96 96
